name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
- title: '🚀 Features'
  labels:
  - 'feature'
  - 'enhancement'
- title: '🐛 Bug Fixes'
  labels:
  - 'fix'
  - 'bugfix'
  - 'bug'
  - 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
    - 'major'
  minor:
    labels:
    - 'minor'
  patch:
    labels:
    - 'patch'
  default: patch
include-labels:
- 'enhancement'
- 'dependencies'
template: |
  ## Changes

  $CHANGES

autolabeler:
- label: bug
  branch:
  - '/^fix[/-].+/'
- label: chore
  branch:
  - '/^chore[/-].+/'
- label: documentation
  files:
  - '*.md'
- label: enhancement
  branch:
  - '/(enhancement|feature)[/-].+/'
